import Groq from 'groq-sdk';
import * as dotenv from 'dotenv';
import type { EvidenceItem } from '../../shared-types/index.js';

dotenv.config();

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

export async function askCodebase(query: string, codebaseContext: string): Promise<string> {
  const systemPrompt = `You are ContextOS, an expert engineering assistant.
You have been provided with the complete contents of a GitHub repository.
Please answer the developer's question based strictly on the provided codebase context.
Always cite specific files or functions in your answer. Focus on factual, grounded technical analysis.`;

  const userPrompt = `--- CODEBASE CONTEXT ---
${codebaseContext}
------------------------

Developer Question: ${query}`;

  try {
    const response = await groq.chat.completions.create({
      model: 'llama-3.3-70b-versatile',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      temperature: 0.3,
      max_tokens: 4096,
    });
    return response.choices[0]?.message?.content || "No answer generated by the LLM.";
  } catch (error: any) {
    console.error("LLM Error:", error);
    return `Error generating response from LLM: ${error.message}`;
  }
}

export async function askReasoningAgent(query: string, evidence: EvidenceItem[]): Promise<string> {
  const systemPrompt = `You are ContextOS, an expert engineering assistant.
You will be provided with a set of retrieved evidence items (like PRs, Slack threads, and Code snippets).
Synthesize a comprehensive, markdown-formatted answer to the developer's question based strictly on this evidence.
When making claims, you MUST cite the source by including its sourceId in brackets (e.g., [gh-pr-482]).`;

  const formattedEvidence = evidence.map((e, index) => {
    return `[Evidence ${index + 1}]
Source ID: ${e.sourceId}
Type: ${e.type}
URL: ${e.url}
Excerpt:
${e.excerpt}
`;
  }).join('\n');

  const userPrompt = `--- RETRIEVED EVIDENCE ---
${formattedEvidence}
------------------------

Developer Question: ${query}`;

  try {
    const response = await groq.chat.completions.create({
      model: 'llama-3.3-70b-versatile',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      temperature: 0.3,
      max_tokens: 4096,
    });
    return response.choices[0]?.message?.content || "No answer generated by the LLM.";
  } catch (error: any) {
    console.error("LLM Error:", error);
    return `Error generating response from LLM: ${error.message}`;
  }
}
